name: Deploy to Render

on:
  push:
    branches: [ main ]  # or `main`, `release`, etc.

jobs:
  deploy:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.web4api.onrender.com }}
